### ISSUE TITLE
The mod changes the scale of crop icons on the map

### ISSUE THREAD

**Issue by vitalii2011** [DennisB97/FS22DroneDelivery#3]
![fsScreen_2023_12_09_18_20_29](https://github.com/DennisB97/FS22DroneDelivery/assets/41552153/85ff7cb5-bae3-410d-8bc5-a10005bbbc8b)

**Comment by DennisB97** [comment]
Thanks for the bug report. 
My mod also caused other car icons to disappear and the vehicle preview image to be too large. 
These will be fixed.

**Comment by DennisB97** [comment]
Now fixed by the commit 32961a89205d4a884c4e6c04bf4d87351c62a183, will take a while before official modhub will have it tested.
