### ISSUE TITLE
There is no way to act and the game will not be saved:

### ISSUE THREAD

**Issue by vitalii2011** [DennisB97/FS22DroneDelivery#6]
```
2024-05-24 15:08 FS22_ConservationAgriculture: Setting limitToField from true to true
2024-05-24 15:09 Error: Running LUA method 'update'.
C:/Users/Mavra/Documents/My Games/FarmingSimulator2022/mods/FS22_DroneDelivery/scripts/misc/droneActionPhase.lua:159: attempt to index field 'owner' (a nil value)
2024-05-24 15:09 Error: Running LUA method 'update'.
C:/Users/Mavra/Documents/My Games/FarmingSimulator2022/mods/FS22_DroneDelivery/scripts/misc/droneActionPhase.lua:159: attempt to index field 'owner' (a nil value)
2024-05-24 15:09 Error: Running LUA method 'update'.
C:/Users/Mavra/Documents/My Games/FarmingSimulator2022/mods/FS22_DroneDelivery/scripts/misc/droneActionPhase.lua:159: attempt to index field 'owner' (a nil value)
2024-05-24 15:09 Error: Running LUA method 'update'.
C:/Users/Mavra/Documents/My Games/FarmingSimulator2022/mods/FS22_DroneDelivery/scripts/misc/droneActionPhase.lua:159: attempt to index field 'owner' (a nil value)
2024-05-24 15:09 Error: Running LUA method 'update'. 

```

**Comment by vitalii2011** [comment]
And another log.txt: the equipment on the field continues to move, but the field is not processed:
[log.txt](https://github.com/DennisB97/FS22DroneDelivery/files/15443884/log.txt)

**Comment by DennisB97** [comment]
Sorry for the very late reply.
I see the issue immediately, I have copy pasted from my other code and forgot to rename something. 
Apparently took quite a while before something went in there and caught that bug. 
I will fix this.

**Comment by vitalii2011** [comment]
Thanks for the answer and clarification.
Don't worry, I remember that you warned about the lack of time for the mod. Everything is fine.
Despite the above, I am able/interested in using it.
If there is a fix, that will be great. :)

**Comment by vitalii2011** [comment]
Thank you! Now everything is perfect, there are no errors in the log. Checked enough time with six drones.
